### ISSUE TITLE
shutdown app read EIO error

### ISSUE THREAD

**Issue by cyphunk** [nocompanyco/monsterinthemiddle#3]
When closing electron application there are some times errors such as the one below. Also the Aprspoof process will some times not give up its port.
```
Error: read EIO
at TTY.onStreamRead (internal/stream_base_commons.js:200:27)
Emitted 'error' event on ReadStream instance at:
at emitErrorNT (internal/streams/destroy.js:92:8)
at emitErrorAndCloseNT (internal/streams/destroy.js:60:3)
at processTicksAndRejections (internal/process/task_queues.js:81:21) {
errno: 'EIO',
code: 'EIO',
syscall: 'read'
}
```

**Comment by cyphunk** [comment]
This also shows up on OSX. Do not have time now but later test:

- remove tty code from packets.js and see if this issue persists when closing electron app. if it is a tty hold issue consider adding flag for not grabbing tty and use the flag when forking the process from electron.js
