### ISSUE TITLE
Linux: libpcap.so.1: cannot open shared object file

### ISSUE THREAD

**Issue by cyphunk** [nocompanyco/monsterinthemiddle#9]
Linux build cannot find shared libpcap on deployed application. Resolve by added 'extraFiles' to package.json. Confirmed on build on archlinux and deploy on Ubuntu 18.04 LTS

```
Error: libpcap.so.1: cannot open shared object file: No such file or directory
    at process.func [as dlopen] (electron/js2c/asar.js:140:31)
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:1034:18)
    at Object.func [as .node] (electron/js2c/asar.js:149:18)
    at Module.load (internal/modules/cjs/loader.js:815:32)
    at Module._load (internal/modules/cjs/loader.js:727:14)
    at Function.Module._load (electron/js2c/asar.js:738:28)
    at Module.require (internal/modules/cjs/loader.js:852:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/home/user/Downloads/monsterinthemiddle-0.1.1-linux-x64/resources/app.asar/node_modules/pcap/pcap.js:3:21)
    at Module._compile (internal/modules/cjs/loader.js:967:30)
```

**Comment by cyphunk** [comment]
fixed by https://github.com/nocompanyco/monsterinthemiddle/commit/af3d79965bdca9ce6a1e5975afa91c6e47557b3b
